api_platform:
  title: 'Greeting Card AI API'
  description: 'API pour la création de cartes de vœux avec IA'
  version: '1.0.0'
  show_webui: true
  show_swagger_ui: true
  swagger:
    api_keys:
      api_key:
        name: Authorization
        type: header
  paths:
    skip_schema_filtering: false
