sonar.projectKey=greeting-card
sonar.projectName=Greeting Card
sonar.sources=angular/src,symfony/src
sonar.host.url=http://localhost:9001
sonar.exclusions=**/mysql_data/**
sonar.javascript.exclusions=**/docker/**,**/mysql_data/**
# sonar.exclusions=**/docker/**,**/mysql_data/**,**/node_modules/**,**/.git/**,**/var/**